config/routes.rb
Rails.application.routes.draw do
  resources :tags
  resources :comments
  resources :trails
  resources :categories
  resources :reports

  devise_for :users

  root 'home#index'

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :sessions, only: [:create] do
        delete :destroy, on: :collection
      end
      resources :reports, only: [:index, :create]
    end
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :comments
  belongs_to :trail
  has_and_belongs_to_many :tags
  belongs_to :user
  belongs_to :category

  acts_as_mappable :default_units => :miles,
                   :distance_field_name => :distance,
                   :lat_column_name => :latitude,
                   :lng_column_name => :longitude

  validates :latitude,
    presence:     true,
    numericality: true

  validates :longitude,
    presence:     true,
    numericality: true

  after_initialize :set_default_reported_at

  def set_default_reported_at
    self.reported_at ||= DateTime.now
  end

  def tags_text
    tags.pluck(:name).join(",")
  end

  def tags_text=(value)
    self.tag_ids = value.split(",").map do |tag_name|
      Tag.where(name: tag_name.strip.downcase).first_or_create.id
    end
  end


  def category_name
    (category) ? category.name : nil
  end
end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < Api::V1::BaseController
  skip_before_action :authenticate_via_token!, only: [:index]

  # CURL example:
  #   curl "localhost:3000/api/v1/reports?radius_miles=5&lat38.835161=&lng=-77.311821"
  #
  def index
    @reports = Report.within(params[:radius_miles], origin: filter_location)
  end

  # CURL example (doesn't include auth headers!):
=begin
     curl -i \
       -H "Content-Type: application/json" \
       -X POST -d '{"reports": [{"latitude":38.835161,"longitude":-77.311821,"description":"created via curl"}]}' \
       "localhost:3000/api/v1/reports?token=xxxx"
=end

  def create
    @reports = reports_params.map {|p| current_user.reports.build(p)}
    success = @reports.map {|report| report.save }
    if success.all?
      head :no_content
    else
      render json: {reports: @reports.map{|report| report.slice(:id, :latitude, :longitude, :errors)}},
        status: :unprocessable_entity
    end
  end

  private

    def reports_params
      params[:reports].map {|p| report_params(p)}
    end

    def report_params(params_hash)
      params_hash.permit(:latitude, :longitude, :description, :reported_at, :category_id, :trail_id)
    end

    def filter_location
      [params[:lat].to_f, params[:lng].to_f]
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = current_user.reports.new
    @report.pictures.build
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = current_user.reports.new(report_params)

    respond_to do |format|
      if @report.save
        # if params[:pictures]
        #   @report.pictures.create(picture: params[:pictures])
        # end
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        # if params[:picture]
        #     @report.pictures.create(picture: picture)
        # end
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(
        :latitude, :longitude, :description, :tags_text, :reported_at,

        # TODO: We might want to perform additional auth checks on these...
        :trail_id, :category_id,
        :pictures_attributes => [:picture]
      )
    end


end

app/helpers/api/v1/reports_helper.rb
module Api::V1::ReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper  
end

app/views/reports/_form.html.erb
<%= form_for(@report, :html => { :multipart => true }) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>

  <%= f.fields_for :pictures do |picture_fields| %>
      <%= image_tag(picture_fields.object.picture.preview.url, alt: picture_fields.object[:picture]) if picture_fields.object[:picture] %>
  <% end %>
  </br></br>
  <div class="control-group">
    <%= f.label :trail %>
    <%= f.collection_select :trail_id, Trail.all, :id, :name, include_blank: "<none>" %>
  </div>

  <div class="control-group">
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: "<none>" %>
  </div>
  <%= f.fields_for :pictures, @report.pictures do |picture_fields| %>
    <div class="control-group">
      <%= picture_fields.label :picture, "Picture" %>
      <%= picture_fields.file_field :picture %>
    </div>
  <% end %>
  <div class="control-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%# <div class="control-group"> %>
  <%#   <%= f.label :reported_at %1> %>
  <%#   <%= f.datetime_select :reported_at %1> %>
  <%# </div> %>
  <div class="control-group">
    <%= f.label :tags_text, "Tags" %>
    <%= f.text_field :tags_text, "placeholder" => "Add tags", "data-role" => "tagsinput" %>
  </div>
  <div class="control-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<%- model_class = Report -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:tags) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= link_to report.id, report_path(report) %></td>
        <td><%= report.latitude %></td>
        <td><%= report.longitude %></td>
        <td><%= report.description %></td>
        <td><%= report.category_name %></td>
        <td><%= report.tags_text %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_report_path(report), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      report_path(report),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_report_path,
            :class => 'btn btn-primary' %>

app/views/reports/new.html.erb
<h1>New report</h1>
<div id="map-canvas" class="map-canvas"></div>
<%= render 'form' %>

<%= link_to 'Back', reports_path %>

<% content_for :javascript do %>
  <%= javascript_include_tag "map" %>
<% end %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @report.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @report.longitude %>
</p>

<p>
  <strong>Description:</strong>
  <%= @report.description %>
</p>

<p>
  <strong>Reported at:</strong>
  <%= @report.reported_at %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>